title: Microsoft Government Low Code Solutions
description: Reusable Dataverse solution modules for Power Platform & D365
logo: /assets/logo.png

# If this is a project site (https://username.github.io/repo), set baseurl to "/repo"
url: "https://username.github.io"
baseurl: ""

# Keep Markdown simple; we’re not using plugins that Pages doesn’t support
markdown: kramdown
permalink: pretty

# Collections
collections:
  solutions:
    output: true
    permalink: /solutions/:title/
  docs:
    output: true
    # :doc is not a Jekyll token; use :basename
    permalink: /solutions/:solution/:basename/
  releases:
    output: true
    permalink: /releases/:solution/:version/
  use_cases:
    output: true
    permalink: /use-cases/:title/
  personas:
    output: true
    permalink: /personas/:title/
  data_models:
    output: true
    permalink: /data-models/:title/
