title: Microsoft GLOWS (Government Low-code Open-source Workforce Solutions)
first: Microsoft Government Low Code, Open Source Solutions
description: MIT Open-source solutions for Power Platform and Dynamics 365
logo: /assets/logo.png

# If this is a project site (https://username.github.io/repo), set baseurl to "/repo"
url: "https://microsoft.github.io"   # host only, no trailing slash
baseurl: "/gov-solutions"             # MUST start with a slash; repo name
repository: "microsoft/gov-solutions" # (nice to have for jekyll-github-metadata)

# Keep Markdown simple; we’re not using plugins that Pages doesn’t support
markdown: kramdown
permalink: pretty

# Collections
collections:
  app_starter_kits:
    output: true
    permalink: /app-starter-kits/:title/
  docs:
    output: true
    # :doc is not a Jekyll token; use :basename
    permalink: /app-starter-kits/:solution/:basename/
  app_releases:
    output: true
    permalink: /app-starter-kits/releases/:path/
  data_model_releases:
    output: true
    permalink: /data-models/releases/:path/
  use_cases:
    output: true
    permalink: /use-cases/:title/
  personas:
    output: true
    permalink: /personas/:title/
  data_models:
    output: true
    permalink: /data-models/:title/
